spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
